server:
  port: 8084

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smartpos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

smartpos:
  app:
    jwtSecret: secureKeyWithAtLeast256BitsForHS256SignatureAlgorithm123456789012345678901234567890
    jwtExpirationMs: 86400000 # 24 hours