server:
  port: 8085

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smartpos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.smartpos.analytics: DEBUG